/**
 * API Route: GTM Playbook Export
 * GET /api/gtm/export?company=X&format=md|json
 *
 * Generates and exports a Living Playbook as downloadable Markdown or JSON.
 */

import { NextRequest, NextResponse } from "next/server";
import { generateLivingPlaybook } from "@/services/gtmPlaybookService";
import type { LivingPlaybook } from "@/data/gtmModels";

// ============================================================================
// MARKDOWN RENDERER
// ============================================================================

function playbookToMarkdown(pb: LivingPlaybook): string {
    const lines: string[] = [];
    const add = (...s: string[]) => s.forEach(l => lines.push(l));

    add(`# GTM Living Playbook — ${pb.companyName}`);
    add(`**Industry:** ${pb.industry}`);
    add(`**Generated:** ${pb.createdAt}`);
    add(`**Status:** ${pb.status}`, '');

    // Company Overview
    add('## Company Overview', '');
    add(`| Field | Value |`);
    add(`|---|---|`);
    add(`| Name | ${pb.company.name} |`);
    add(`| Industry | ${pb.company.industry} |`);
    add(`| Size | ${pb.company.size} |`);
    add(`| Founded | ${pb.company.founded} |`);
    add(`| HQ | ${pb.company.headquarters || 'N/A'} |`);
    add('');

    // SWOT Analysis
    if (pb.swotAnalysis) {
        add('## SWOT Analysis', '');
        add('### Strengths 💪');
        pb.swotAnalysis.strengths.forEach(s => add(`- ${s}`));
        add('');
        add('### Weaknesses ⚠️');
        pb.swotAnalysis.weaknesses.forEach(s => add(`- ${s}`));
        add('');
        add('### Opportunities 🚀');
        pb.swotAnalysis.opportunities.forEach(s => add(`- ${s}`));
        add('');
        add('### Threats 🛡️');
        pb.swotAnalysis.threats.forEach(s => add(`- ${s}`));
        add('');
    }

    // Customer Segmentation
    add('## Customer Segmentation', '');
    add(`**ICP Summary:** ${pb.customerSegmentation.icpSummary}`, '');
    pb.customerSegmentation.personas.forEach((p, i) => {
        add(`### Persona ${i + 1}: ${p.name}`);
        add(`- **Role:** ${p.role}`);
        add(`- **Company Size:** ${p.companySize}`);
        add(`- **Match Score:** ${p.matchScore}%`);
        add(`- **Pain Points:** ${p.painPoints.join(', ')}`);
        add(`- **Goals:** ${p.goals.join(', ')}`);
        add(`- **Channels:** ${p.channels.join(', ')}`);
        add('');
    });

    // Competitive Landscape
    add('## Competitive Landscape', '');
    add('| Competitor | Positioning | Threat |');
    add('|---|---|---|');
    pb.competitiveTracker.competitors.forEach(c => {
        add(`| ${c.name} | ${c.positioning} | ${c.threatLevel} |`);
    });
    add('');
    add(`**Differentiators:** ${pb.competitiveTracker.differentiators.join(', ')}`, '');

    // Market Reports
    add('## Market Reports', '');
    pb.marketReports.forEach(r => {
        add(`### ${r.topic}`);
        add(`${r.summary}`, '');
        add('**Key Findings:**');
        r.keyFindings.forEach(f => add(`- ${f}`));
        add('');
    });

    // Scenarios
    add('## Scenario Models', '');
    pb.scenarioModels.forEach(s => {
        add(`### ${s.name}`);
        add(`${s.description}`, '');
        add('**Assumptions:**');
        s.assumptions.forEach(a => add(`- ${a}`));
        add('');
        add('**Recommended Actions:**');
        s.recommendedActions.forEach(a => add(`- ${a}`));
        add('');
        add('**Risks:**');
        s.risks.forEach(r => add(`- ${r}`));
        add('');
    });

    // GTM Recommendation
    add('## GTM Recommendation', '');
    add(`**Strategy:** ${pb.gtmRecommendation.recommendedStrategy}`);
    add(`**Rationale:** ${pb.gtmRecommendation.rationale}`, '');
    add('**Next Steps:**');
    pb.nextSteps.forEach((s, i) => add(`${i + 1}. ${s}`));
    add('');

    // Timeline
    add('## Timeline', '');
    add(`- **Phase 1:** ${pb.timeline.phase1}`);
    add(`- **Phase 2:** ${pb.timeline.phase2}`);
    add(`- **Phase 3:** ${pb.timeline.phase3}`);
    add('');

    // Data Sources
    add('## Data Sources', '');
    pb.validationSources.forEach(s => {
        add(`- **${s.source}** (${s.type}) — confidence: ${s.confidence}%, ${s.dataPoints} data points`);
    });
    add('');
    add('---');
    add(`*Generated by VICO — Vietnam Copilot Platform*`);

    return lines.join('\n');
}

// ============================================================================
// GET — Export Playbook
// ============================================================================

export async function GET(request: NextRequest) {
    try {
        const searchParams = request.nextUrl.searchParams;
        const company = searchParams.get("company");
        const format = searchParams.get("format") || "md";

        if (!company || company.length < 2) {
            return NextResponse.json(
                { error: "Company name required (?company=X)" },
                { status: 400 }
            );
        }

        if (!["md", "json"].includes(format)) {
            return NextResponse.json(
                { error: "Format must be 'md' or 'json'" },
                { status: 400 }
            );
        }

        // Generate the playbook (cache will be used if available)
        const playbook = await generateLivingPlaybook(company, ["Vietnam"]);

        if (format === "json") {
            return new NextResponse(JSON.stringify(playbook, null, 2), {
                status: 200,
                headers: {
                    "Content-Type": "application/json",
                    "Content-Disposition": `attachment; filename="gtm-${company.toLowerCase().replace(/\s+/g, '-')}.json"`,
                },
            });
        }

        // Markdown
        const markdown = playbookToMarkdown(playbook);
        return new NextResponse(markdown, {
            status: 200,
            headers: {
                "Content-Type": "text/markdown; charset=utf-8",
                "Content-Disposition": `attachment; filename="gtm-${company.toLowerCase().replace(/\s+/g, '-')}.md"`,
            },
        });
    } catch (error) {
        console.error("GTM export error:", error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : "Export failed" },
            { status: 500 }
        );
    }
}
