/**
 * 🎯 Competitor Intelligence Service — AI-Powered (Gemini 2.0 Flash)
 * 
 * Generates competitor analysis using:
 * 1. Real company data from CSV/database (name, industry, products, location, size)
 * 2. Gemini AI for strategic analysis (SWOT, positioning, battlecards)
 * 3. Clearly labeled confidence levels — no fabricated numbers presented as fact
 * 
 * Data provenance:
 * - "database"    = from VICO company database (CSV)
 * - "ai_analysis" = generated by Gemini based on company context
 * - "estimated"   = industry-average fallback (when AI unavailable)
 */

import { GoogleGenAI } from '@google/genai';
import { loadAllCompanies, NormalizedCompany } from './competitorEngine';

// ============================================================================
// TYPES
// ============================================================================

export interface CompetitorIntelligenceInput {
    userCompany: {
        name: string;
        industry: string;
        description: string;
        products: string;
        location: string;
        size: string;
    };
    selectedCompetitors: Array<{
        name: string;
        industry?: string;
        similarity?: number;
        products?: string;
        intro?: string;
        address?: string;
        size?: string;
        source?: string;
        website?: string;
        // Rich fields from company database (Phase 15+)
        year?: number;
        revenue?: string;
        headcount?: number;
        total_funding?: string;
        employee_range?: string;
    }>;
}

export interface CompetitorProfile {
    id: string;
    name: string;
    logo: string;
    industry: string;
    similarity: number;
    source: string;
    dataSource: 'database' | 'ai_analysis' | 'estimated';

    firmographics: {
        revenue: string;
        revenueGrowth: number;
        headcount: number;
        headcountGrowth: number;
        headcountHistory: number[];
        funding: {
            total: string;
            lastRound: string;
            lastRoundDate: string;
            investors: string[];
        };
        hq: string;
        offices: string[];
        foundedYear: number;
        website: string;
        confidence: 'verified' | 'ai_estimated' | 'industry_average';
    };

    techStack: {
        cloud: string[];
        frontend: string[];
        backend: string[];
        database: string[];
        analytics: string[];
        other: string[];
    };

    positioning: {
        x: number;
        y: number;
        quadrant: 'Leader' | 'Challenger' | 'Niche' | 'Visionary';
        marketShare: number;
    };

    swot: {
        strengths: string[];
        weaknesses: string[];
        opportunities: string[];
        threats: string[];
    };

    gtmStrategy: {
        targetSegment: 'SME' | 'Enterprise' | 'Both';
        salesModel: 'Direct' | 'Partner' | 'PLG' | 'Hybrid';
        pricingModel: string;
        keyChannels: string[];
    };

    battlecard: {
        whyWeWin: string[];
        whyWeLose: string[];
        killPoints: string[];
        landmines: string[];
        objectionHandlers: Array<{ objection: string; response: string }>;
    };

    featureComparison: Array<{
        feature: string;
        category: string;
        us: boolean | 'partial';
        them: boolean | 'partial';
        notes: string;
    }>;

    signals: {
        hiringTrends: Array<{
            role: string;
            count: number;
            change: number;
            signal: string;
        }>;
        websiteChanges: Array<{
            type: string;
            date: string;
            description: string;
            impact: 'High' | 'Medium' | 'Low';
        }>;
        newsSentiment: {
            positive: number;
            neutral: number;
            negative: number;
            trend: 'up' | 'down' | 'stable';
            recentHeadlines: string[];
        };
    };

    digitalFootprint: {
        monthlyTraffic: string;
        trafficGrowth: number;
        trafficSources: Array<{ source: string; percentage: number }>;
        topKeywords: Array<{ keyword: string; position: number; volume: number }>;
        socialMetrics: {
            linkedin: { followers: number; engagement: number };
            facebook: { followers: number; engagement: number };
            twitter: { followers: number; engagement: number };
        };
        contentStrategy: string[];
    };
}

export interface CompetitorIntelligenceReport {
    generatedAt: string;
    userCompany: string;
    industry: string;
    totalCompetitors: number;
    competitors: CompetitorProfile[];
    marketPositioningMap: {
        quadrants: {
            leaders: string[];
            challengers: string[];
            niche: string[];
            visionaries: string[];
        };
        avgPrice: number;
        avgFeatures: number;
    };
    industryOverview: {
        totalPlayers: number;
        avgRevenue: string;
        avgHeadcount: number;
        topTechStacks: Array<{ tech: string; adoption: number }>;
    };
    executiveSummary: {
        overview: string;
        keyFindings: string[];
        recommendations: string[];
    };
    dataSources: string[];
}

// ============================================================================
// GEMINI CLIENT
// ============================================================================

function getGemini(): GoogleGenAI | null {
    try {
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) return null;
        return new GoogleGenAI({ apiKey });
    } catch {
        return null;
    }
}

// Simple in-memory cache (TTL 30 min)
const aiCache = new Map<string, { data: any; ts: number }>();
const CACHE_TTL = 30 * 60 * 1000;

function getCached(key: string): any | null {
    const entry = aiCache.get(key);
    if (!entry) return null;
    if (Date.now() - entry.ts > CACHE_TTL) { aiCache.delete(key); return null; }
    return entry.data;
}

function setCache(key: string, data: any): void {
    aiCache.set(key, { data, ts: Date.now() });
    if (aiCache.size > 100) {
        const oldest = [...aiCache.entries()].sort((a, b) => a[1].ts - b[1].ts)[0];
        if (oldest) aiCache.delete(oldest[0]);
    }
}

// ============================================================================
// GEMINI AI ANALYSIS
// ============================================================================

interface GeminiCompetitorAnalysis {
    firmographics: {
        estimatedRevenue: string;
        revenueGrowth: number;
        estimatedHeadcount: number;
        headcountGrowth: number;
        fundingInfo: string;
        lastRound: string;
        lastRoundDate: string;
        investors: string[];
        foundedYear: number;
        offices: string[];
    };
    techStack: {
        cloud: string[];
        frontend: string[];
        backend: string[];
        database: string[];
        analytics: string[];
    };
    positioning: {
        quadrant: string;
        marketShareEstimate: number;
        priceLevel: number;
        featureRichness: number;
    };
    swot: {
        strengths: string[];
        weaknesses: string[];
        opportunities: string[];
        threats: string[];
    };
    gtm: {
        targetSegment: string;
        salesModel: string;
        pricingModel: string;
        keyChannels: string[];
    };
    battlecard: {
        whyUserWins: string[];
        whyUserLoses: string[];
        killPoints: string[];
        objections: Array<{ objection: string; response: string }>;
    };
    digitalPresence: {
        estimatedTraffic: string;
        contentTypes: string[];
        socialChannels: string[];
    };
    confidence: number;
}

async function analyzeCompetitorWithGemini(
    userCompany: CompetitorIntelligenceInput['userCompany'],
    competitor: CompetitorIntelligenceInput['selectedCompetitors'][0],
    industryContext: { totalPlayers: number; industry: string }
): Promise<GeminiCompetitorAnalysis | null> {
    const ai = getGemini();
    if (!ai) return null;

    const cacheKey = `ci_${userCompany.name}_${competitor.name}`.toLowerCase().replace(/\s+/g, '_');
    const cached = getCached(cacheKey);
    if (cached) {
        console.log(`   📦 Cache hit: ${competitor.name}`);
        return cached;
    }

    const prompt = `You are a competitive intelligence analyst specializing in the Vietnamese market.

IMPORTANT RULES:
- Only state facts you are reasonably confident about from public knowledge
- For financial data, always say "estimated" and give a range
- If you don't know something, say "unknown" — do NOT fabricate
- Focus on publicly available information about these companies

YOUR COMPANY (the client):
- Name: ${userCompany.name}
- Industry: ${userCompany.industry}
- Description: ${userCompany.description}
- Products: ${userCompany.products}
- Location: ${userCompany.location}
- Size: ${userCompany.size}

COMPETITOR TO ANALYZE:
- Name: ${competitor.name}
- Industry: ${competitor.industry || userCompany.industry}
- Products/Services: ${competitor.products || 'unknown'}
- Description: ${competitor.intro || 'unknown'}
- Address: ${competitor.address || 'unknown'}
- Size: ${competitor.size || 'unknown'}
- Website: ${competitor.website || 'unknown'}

INDUSTRY CONTEXT:
- ${industryContext.totalPlayers} companies in ${industryContext.industry} sector in Vietnam

Provide a competitive intelligence analysis. Return ONLY valid JSON (no markdown, no backticks) with this exact structure:
{
  "firmographics": {
    "estimatedRevenue": "$XM (estimated)" or "unknown",
    "revenueGrowth": number or 0,
    "estimatedHeadcount": number or 0,
    "headcountGrowth": number or 0,
    "fundingInfo": "description" or "unknown",
    "lastRound": "Series X" or "unknown",
    "lastRoundDate": "Q1 2024" or "unknown",
    "investors": ["investor1"] or [],
    "foundedYear": number or 0,
    "offices": ["city1"]
  },
  "techStack": {
    "cloud": ["AWS"],
    "frontend": ["React"],
    "backend": ["Node.js"],
    "database": ["PostgreSQL"],
    "analytics": ["GA4"]
  },
  "positioning": {
    "quadrant": "Leader" | "Challenger" | "Niche" | "Visionary",
    "marketShareEstimate": number (0-25),
    "priceLevel": number (0-100),
    "featureRichness": number (0-100)
  },
  "swot": {
    "strengths": ["specific strength based on their known products/market position"],
    "weaknesses": ["specific weakness"],
    "opportunities": ["specific opportunity"],
    "threats": ["specific threat from ${userCompany.name}"]
  },
  "gtm": {
    "targetSegment": "SME" | "Enterprise" | "Both",
    "salesModel": "Direct" | "Partner" | "PLG" | "Hybrid",
    "pricingModel": "description",
    "keyChannels": ["channel1"]
  },
  "battlecard": {
    "whyUserWins": ["specific reason ${userCompany.name} beats ${competitor.name}"],
    "whyUserLoses": ["specific reason ${competitor.name} beats ${userCompany.name}"],
    "killPoints": ["specific question to ask prospect to expose competitor weakness"],
    "objections": [{"objection": "specific objection", "response": "counter"}]
  },
  "digitalPresence": {
    "estimatedTraffic": "XK/month (estimated)" or "unknown",
    "contentTypes": ["Blog", "Case studies"],
    "socialChannels": ["LinkedIn", "Facebook"]
  },
  "confidence": number (0-100, how confident you are in this analysis)
}

Be specific to ${competitor.name}'s actual business. Use Vietnamese for SWOT and battlecard text.`;

    // Retry with backoff for 429 rate limits (max 2 retries, 5s/10s delays)
    const MAX_RETRIES = 2;
    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
            const { generateWithFallback } = await import('./geminiHelper');
            const result = await generateWithFallback({
                contents: prompt,
                config: {
                    temperature: 0.3,
                    maxOutputTokens: 2000,
                    tools: [{ googleSearch: {} }],
                }
            });

            const text = result.text || '';
            const jsonMatch = text.match(/\{[\s\S]*\}/);
            if (!jsonMatch) {
                console.warn(`   ⚠️ Gemini returned non-JSON for ${competitor.name}`);
                return null;
            }

            const parsed = JSON.parse(jsonMatch[0]) as GeminiCompetitorAnalysis;
            setCache(cacheKey, parsed);
            console.log(`   🤖 AI analysis complete: ${competitor.name} (confidence: ${parsed.confidence}%, via ${result.model})`);
            return parsed;
        } catch (err: any) {
            const is429 = err?.status === 429 || err?.message?.includes('429') || err?.message?.includes('quota');
            if (is429 && attempt < MAX_RETRIES) {
                const delay = (attempt + 1) * 5000; // 5s, 10s
                console.warn(`   ⏳ Gemini rate-limited for ${competitor.name}, retry ${attempt + 1}/${MAX_RETRIES} in ${delay / 1000}s...`);
                await new Promise(r => setTimeout(r, delay));
                continue;
            }
            console.error(`   ❌ Gemini error for ${competitor.name}:`, err?.message || err);
            return null;
        }
    }
    return null;
}

async function generateExecutiveSummary(
    userCompany: CompetitorIntelligenceInput['userCompany'],
    competitors: CompetitorProfile[],
    industryContext: { totalPlayers: number; industry: string }
): Promise<{ overview: string; keyFindings: string[]; recommendations: string[] }> {
    const ai = getGemini();

    const competitorSummary = competitors.map(c =>
        `${c.name} (${c.positioning.quadrant}, similarity: ${c.similarity}%, ${c.firmographics.revenue})`
    ).join('\n');

    if (!ai) {
        return buildFallbackSummary(userCompany, competitors, industryContext);
    }

    // Retry with exponential backoff for 429 rate limits
    for (let attempt = 0; attempt <= 2; attempt++) {
        try {
            const { generateWithFallback } = await import('./geminiHelper');
            const result = await generateWithFallback({
                contents: `You are a strategic analyst. Write a concise executive summary for ${userCompany.name} about their competitive landscape in ${industryContext.industry} in Vietnam.

Competitors analyzed:
${competitorSummary}

Industry has ${industryContext.totalPlayers} total players.

Return ONLY valid JSON:
{
  "overview": "2-3 sentence overview in Vietnamese",
  "keyFindings": ["finding1", "finding2", "finding3", "finding4"],
  "recommendations": ["rec1", "rec2", "rec3"]
}

Use Vietnamese. Be specific and actionable.`,
                config: { temperature: 0.4, maxOutputTokens: 1000, tools: [{ googleSearch: {} }] }
            });

            const text = result.text || '';
            const jsonMatch = text.match(/\{[\s\S]*\}/);
            if (jsonMatch) {
                return JSON.parse(jsonMatch[0]);
            }
            break;
        } catch (err: any) {
            const is429 = err?.status === 429 || err?.message?.includes('429') || err?.message?.includes('quota');
            if (is429 && attempt < 2) {
                const delay = (attempt + 1) * 5000; // 5s, 10s
                console.warn(`   ⏳ Gemini rate-limited for exec summary, retry ${attempt + 1}/2 in ${delay / 1000}s...`);
                await new Promise(r => setTimeout(r, delay));
                continue;
            }
            console.warn('   ⚠️ Gemini exec summary failed, using fallback');
        }
    }

    return buildFallbackSummary(userCompany, competitors, industryContext);
}

function buildFallbackSummary(
    userCompany: CompetitorIntelligenceInput['userCompany'],
    competitors: CompetitorProfile[],
    industryContext: { totalPlayers: number; industry: string }
): { overview: string; keyFindings: string[]; recommendations: string[] } {
    const avgSimilarity = competitors.length > 0
        ? competitors.reduce((sum, c) => sum + c.similarity, 0) / competitors.length
        : 0;
    const topComp = competitors.length > 0
        ? competitors.reduce((max, c) => c.similarity > max.similarity ? c : max, competitors[0])
        : null;
    const leaders = competitors.filter(c => c.positioning.quadrant === 'Leader');
    const challengers = competitors.filter(c => c.positioning.quadrant === 'Challenger');

    return {
        overview: `Phân tích ${competitors.length} đối thủ cạnh tranh trong ngành ${industryContext.industry} cho ${userCompany.name}. ` +
            `Độ tương đồng trung bình: ${avgSimilarity.toFixed(0)}%. ` +
            (topComp ? `${topComp.name} là đối thủ đáng chú ý nhất (similarity ${topComp.similarity}%). ` : '') +
            `Thị trường có ${industryContext.totalPlayers.toLocaleString()} công ty.`,
        keyFindings: [
            `${leaders.length} đối thủ ở vị thế Leader — cần chiến lược differentiation`,
            `${challengers.length} Challengers đang tăng trưởng — theo dõi sát`,
            topComp ? `Đối thủ gần nhất: ${topComp.name} (${topComp.industry})` : 'Chưa có dữ liệu đối thủ',
            `Dữ liệu được phân tích bằng AI — một số ước tính cần xác minh thêm`,
        ],
        recommendations: [
            topComp ? `Focus differentiation vs ${topComp.name} — tìm lợi thế cạnh tranh riêng` : 'Xác định và theo dõi đối thủ chính',
            `Xây dựng case studies với khách hàng VN để tăng uy tín`,
            `Theo dõi hoạt động tuyển dụng của đối thủ để dự đoán chiến lược`,
        ]
    };
}

// ============================================================================
// INDUSTRY NORMALIZATION
// ============================================================================

function normalizeIndustry(industry: string): string {
    const directMatch: Record<string, string> = {
        'tech': 'Technology', 'technology': 'Technology', 'it': 'Technology', 'software': 'Technology',
        'saas': 'Technology', 'ai': 'Technology', 'fintech': 'Finance', 'finance': 'Finance',
        'banking': 'Finance', 'ecommerce': 'Retail', 'e-commerce': 'Retail', 'retail': 'Retail',
        'healthcare': 'Healthcare', 'health': 'Healthcare', 'medtech': 'Healthcare',
        'education': 'Education', 'edtech': 'Education', 'logistics': 'Logistics',
        'manufacturing': 'Manufacturing', 'automotive': 'Automotive',
        'telecommunications': 'Telecommunications', 'telecom': 'Telecommunications',
        'realestate': 'RealEstate', 'energy': 'Energy', 'foodbeverage': 'FoodBeverage',
        'entertainment': 'Entertainment', 'agriculture': 'Agriculture',
        'construction': 'Construction', 'tourism': 'Tourism', 'insurance': 'Insurance',
        'consulting': 'Consulting', 'pharmaceutical': 'Pharmaceutical', 'aerospace': 'Aerospace',
        'gaming': 'Gaming', 'cybersecurity': 'Cybersecurity', 'blockchain': 'Blockchain',
        'media': 'Media', 'fashion': 'Fashion', 'sports': 'Sports', 'legal': 'Legal',
        'humanresources': 'HumanResources', 'marketing': 'Marketing',
        'environmentaltech': 'EnvironmentalTech'
    };
    const key = industry.toLowerCase().replace(/[\s_-]/g, '');
    const normalized = directMatch[key] || industry;
    return normalized.charAt(0).toUpperCase() + normalized.slice(1);
}

// ============================================================================
// PROFILE BUILDER — combines AI analysis with real database data
// ============================================================================

function buildProfile(
    index: number,
    competitor: CompetitorIntelligenceInput['selectedCompetitors'][0],
    userCompany: CompetitorIntelligenceInput['userCompany'],
    aiAnalysis: GeminiCompetitorAnalysis | null,
    industry: string,
): CompetitorProfile {
    const similarity = competitor.similarity || 50;
    const hasAI = !!aiAnalysis;
    const ai = aiAnalysis;

    const headcount = ai?.firmographics?.estimatedHeadcount
        || (competitor as any).headcount
        || parseSizeToNumber(competitor.size);
    const foundedYear = ai?.firmographics?.foundedYear
        || (competitor as any).year
        || 0;
    const dbRevenue = (competitor as any).revenue;
    const dbFunding = (competitor as any).total_funding;

    const profile: CompetitorProfile = {
        id: `comp-${index}`,
        name: competitor.name,
        logo: competitor.name?.substring(0, 2).toUpperCase() || 'CP',
        industry: competitor.industry || industry,
        similarity,
        source: competitor.source || 'csv',
        dataSource: hasAI ? 'ai_analysis' : (dbRevenue ? 'database' : 'estimated'),

        firmographics: {
            revenue: ai?.firmographics?.estimatedRevenue || dbRevenue || 'Undisclosed',
            revenueGrowth: ai?.firmographics?.revenueGrowth || 0,
            headcount,
            headcountGrowth: ai?.firmographics?.headcountGrowth || 0,
            headcountHistory: buildHeadcountHistory(headcount, ai?.firmographics?.headcountGrowth || 0),
            funding: {
                total: ai?.firmographics?.fundingInfo || dbFunding || 'Undisclosed',
                lastRound: ai?.firmographics?.lastRound || 'N/A',
                lastRoundDate: ai?.firmographics?.lastRoundDate || 'N/A',
                investors: ai?.firmographics?.investors || [],
            },
            hq: competitor.address || (ai?.firmographics?.offices?.[0] || 'Vietnam'),
            offices: ai?.firmographics?.offices || [competitor.address || 'Vietnam'].filter(Boolean),
            foundedYear: foundedYear || 0,
            website: competitor.website || '',
            confidence: hasAI ? 'ai_estimated' : (dbRevenue ? 'verified' : 'industry_average'),
        },

        techStack: ai?.techStack ? {
            ...ai.techStack,
            other: [],
        } : {
            cloud: [], frontend: [], backend: [],
            database: [], analytics: [], other: [],
        },

        positioning: {
            x: ai?.positioning?.priceLevel ?? (30 + similarity * 0.4),
            y: ai?.positioning?.featureRichness ?? (20 + similarity * 0.5),
            quadrant: parseQuadrant(ai?.positioning?.quadrant) || inferQuadrant(similarity, index),
            marketShare: ai?.positioning?.marketShareEstimate ?? 0,
        },

        swot: ai?.swot ? {
            strengths: ai.swot.strengths?.slice(0, 5) || [],
            weaknesses: ai.swot.weaknesses?.slice(0, 4) || [],
            opportunities: ai.swot.opportunities?.slice(0, 4) || [],
            threats: ai.swot.threats?.slice(0, 4) || [],
        } : {
            strengths: [`${competitor.name} hoạt động trong ngành ${industry}`],
            weaknesses: ['Cần thu thập thêm dữ liệu để đánh giá'],
            opportunities: ['Thị trường Việt Nam đang tăng trưởng'],
            threats: [`Cạnh tranh từ ${userCompany.name}`],
        },

        gtmStrategy: {
            targetSegment: parseSegment(ai?.gtm?.targetSegment) || 'Both',
            salesModel: parseSalesModel(ai?.gtm?.salesModel) || 'Hybrid',
            pricingModel: ai?.gtm?.pricingModel || 'Undisclosed',
            keyChannels: ai?.gtm?.keyChannels || [],
        },

        battlecard: ai?.battlecard ? {
            whyWeWin: ai.battlecard.whyUserWins?.slice(0, 5) || [],
            whyWeLose: ai.battlecard.whyUserLoses?.slice(0, 4) || [],
            killPoints: ai.battlecard.killPoints?.slice(0, 4) || [],
            landmines: [],
            objectionHandlers: ai.battlecard.objections?.slice(0, 3) || [],
        } : {
            whyWeWin: ['Cần phân tích thêm để xác định lợi thế'],
            whyWeLose: ['Cần phân tích thêm'],
            killPoints: [],
            landmines: [],
            objectionHandlers: [],
        },

        featureComparison: [],

        signals: {
            hiringTrends: [],
            websiteChanges: [],
            newsSentiment: {
                positive: 0, neutral: 0, negative: 0,
                trend: 'stable',
                recentHeadlines: [],
            },
        },

        digitalFootprint: {
            monthlyTraffic: ai?.digitalPresence?.estimatedTraffic || 'N/A',
            trafficGrowth: 0,
            trafficSources: [],
            topKeywords: [],
            socialMetrics: {
                linkedin: { followers: 0, engagement: 0 },
                facebook: { followers: 0, engagement: 0 },
                twitter: { followers: 0, engagement: 0 },
            },
            contentStrategy: ai?.digitalPresence?.contentTypes || [],
        },
    };

    return profile;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

function parseSizeToNumber(size?: string): number {
    if (!size) return 0;
    const rangeMatch = size.match(/(\d+)\s*[-–]\s*(\d+)/);
    if (rangeMatch) return Math.round((parseInt(rangeMatch[1]) + parseInt(rangeMatch[2])) / 2);
    const match = size.match(/(\d[\d,]*)/);
    if (!match) return 0;
    return parseInt(match[1].replace(/,/g, ''), 10);
}

function buildHeadcountHistory(current: number, growth: number): number[] {
    if (current <= 0) return [];
    const history: number[] = [];
    let count = current;
    for (let i = 0; i < 6; i++) {
        history.unshift(Math.round(count));
        count = count / (1 + (growth || 5) / 100 / 2);
    }
    return history;
}

function parseQuadrant(q?: string): 'Leader' | 'Challenger' | 'Niche' | 'Visionary' | null {
    if (!q) return null;
    const map: Record<string, 'Leader' | 'Challenger' | 'Niche' | 'Visionary'> = {
        leader: 'Leader', challenger: 'Challenger', niche: 'Niche', visionary: 'Visionary'
    };
    return map[q.toLowerCase()] || null;
}

function inferQuadrant(similarity: number, index: number): 'Leader' | 'Challenger' | 'Niche' | 'Visionary' {
    if (similarity > 70) return 'Leader';
    if (similarity > 55) return index % 2 === 0 ? 'Challenger' : 'Leader';
    if (similarity > 40) return 'Niche';
    return 'Visionary';
}

function parseSegment(s?: string): 'SME' | 'Enterprise' | 'Both' | null {
    if (!s) return null;
    const lower = s.toLowerCase();
    if (lower.includes('sme') || lower.includes('small')) return 'SME';
    if (lower.includes('enterprise') || lower.includes('large')) return 'Enterprise';
    if (lower.includes('both') || lower.includes('all')) return 'Both';
    return null;
}

function parseSalesModel(s?: string): 'Direct' | 'Partner' | 'PLG' | 'Hybrid' | null {
    if (!s) return null;
    const lower = s.toLowerCase();
    if (lower.includes('direct')) return 'Direct';
    if (lower.includes('partner') || lower.includes('channel')) return 'Partner';
    if (lower.includes('plg') || lower.includes('product-led')) return 'PLG';
    if (lower.includes('hybrid') || lower.includes('mix')) return 'Hybrid';
    return null;
}

// ============================================================================
// MAIN SERVICE FUNCTION
// ============================================================================

export async function generateCompetitorIntelligence(
    input: CompetitorIntelligenceInput
): Promise<CompetitorIntelligenceReport> {
    const startTime = Date.now();
    console.log('🎯 Generating Competitor Intelligence Report (AI-powered)...');
    console.log(`   Company: ${input.userCompany.name}`);
    console.log(`   Industry: ${input.userCompany.industry}`);
    console.log(`   Competitors: ${input.selectedCompetitors.length}`);

    const industry = normalizeIndustry(input.userCompany.industry);

    // Load real company data for industry context
    const allCompanies = await loadAllCompanies();
    const industryPeers = allCompanies.filter(c => normalizeIndustry(c.industry) === industry);
    const industryContext = { totalPlayers: industryPeers.length, industry };

    // Track data sources used
    const dataSources: string[] = ['VICO Company Database (10,000+ companies)'];
    const hasGemini = !!getGemini();
    if (hasGemini) dataSources.push('Gemini 2.0 Flash AI Analysis');
    else dataSources.push('Fallback: industry estimates (GEMINI_API_KEY not set)');

    // Analyze each competitor with Gemini (batches of 3 to avoid rate limits)
    const aiResults: (GeminiCompetitorAnalysis | null)[] = [];
    for (let i = 0; i < input.selectedCompetitors.length; i += 3) {
        const batch = input.selectedCompetitors.slice(i, i + 3);
        const batchResults = await Promise.all(
            batch.map(comp => analyzeCompetitorWithGemini(input.userCompany, comp, industryContext))
        );
        aiResults.push(...batchResults);
    }

    // Build profiles combining database data + AI analysis
    const competitors = input.selectedCompetitors.map((comp, idx) =>
        buildProfile(idx, comp, input.userCompany, aiResults[idx], industry)
    );

    // Classify into quadrants
    const quadrants = { leaders: [] as string[], challengers: [] as string[], niche: [] as string[], visionaries: [] as string[] };
    competitors.forEach(c => {
        if (c.positioning.quadrant === 'Leader') quadrants.leaders.push(c.name);
        else if (c.positioning.quadrant === 'Challenger') quadrants.challengers.push(c.name);
        else if (c.positioning.quadrant === 'Niche') quadrants.niche.push(c.name);
        else quadrants.visionaries.push(c.name);
    });

    // Executive summary
    const execSummary = await generateExecutiveSummary(input.userCompany, competitors, industryContext);

    const elapsed = Date.now() - startTime;
    const aiCount = aiResults.filter(Boolean).length;
    console.log(`✅ Competitor Intelligence Report generated in ${elapsed}ms`);
    console.log(`   AI analyzed: ${aiCount}/${input.selectedCompetitors.length} competitors`);
    if (!hasGemini) console.log('   ⚠️ GEMINI_API_KEY not set — using industry estimates only');

    return {
        generatedAt: new Date().toISOString(),
        userCompany: input.userCompany.name,
        industry,
        totalCompetitors: competitors.length,
        competitors,
        marketPositioningMap: {
            quadrants,
            avgPrice: competitors.length > 0
                ? competitors.reduce((s, c) => s + c.positioning.x, 0) / competitors.length
                : 50,
            avgFeatures: competitors.length > 0
                ? competitors.reduce((s, c) => s + c.positioning.y, 0) / competitors.length
                : 50,
        },
        industryOverview: {
            totalPlayers: industryPeers.length,
            avgRevenue: 'Xem từng đối thủ (AI estimated)',
            avgHeadcount: 0,
            topTechStacks: [],
        },
        executiveSummary: execSummary,
        dataSources,
    };
}

export default {
    generateCompetitorIntelligence
};
