/**
 * 🎯 Customer Insights Service — AI-Powered (Gemini 2.0 Flash)
 * 
 * Generates customer insights using:
 * 1. Real company data from CSV/database (name, industry, products, location, size)
 * 2. Gemini AI for deep customer understanding (personas, pain points, buying process)
 * 3. Clearly labeled data provenance — no fabricated statistics presented as fact
 * 
 * Data provenance:
 * - "ai_analysis"     = generated by Gemini based on company + industry context
 * - "industry_data"   = derived from real company database industry stats
 * - "estimated"       = fallback when AI unavailable
 */

import { GoogleGenAI } from '@google/genai';
import { loadAllCompanies, NormalizedCompany } from './competitorEngine';

// ============================================================================
// TYPES (backward-compatible with frontend CustomerInsightsPage.tsx)
// ============================================================================

export interface IdealCustomerProfile {
    firmographics: {
        companySize: string[];
        industries: string[];
        regions: string[];
        annualRevenue: string;
        employeeCount: string;
        techMaturity: 'Early Adopter' | 'Mainstream' | 'Laggard';
    };
    decisionMakers: Array<{
        title: string;
        role: 'Economic Buyer' | 'Technical Buyer' | 'User Buyer' | 'Champion';
        concerns: string[];
        successMetrics: string[];
    }>;
    keyInfluencers: Array<{
        title: string;
        influence: 'High' | 'Medium' | 'Low';
        focus: string;
    }>;
}

export interface UserPersona {
    name: string;
    title: string;
    avatar: string;
    age: string;
    background: string;
    goals: string[];
    frustrations: string[];
    preferredChannels: string[];
    quote: string;
    dayInLife: string[];
    techStack: string[];
}

export interface PainPoint {
    category: string;
    pain: string;
    severity: 'Critical' | 'High' | 'Medium' | 'Low';
    frequency: string;
    currentSolution: string;
    costOfInaction: string;
}

export interface TriggerEvent {
    event: string;
    urgency: 'Immediate' | 'Short-term' | 'Long-term';
    likelihood: number;
    signals: string[];
    approach: string;
}

export interface BuyingStage {
    stage: string;
    description: string;
    duration: string;
    activities: string[];
    contentNeeded: string[];
    objections: string[];
    successCriteria: string;
}

export interface PurchaseBarrier {
    barrier: string;
    category: 'Price' | 'Trust' | 'Complexity' | 'Timing' | 'Politics' | 'Competition';
    severity: 'High' | 'Medium' | 'Low';
    overcomingStrategy: string;
    proofPoints: string[];
}

export interface CustomerObjection {
    objection: string;
    frequency: number;
    category: string;
    response: string;
    proofPoints: string[];
}

export interface FeatureRequest {
    feature: string;
    votes: number;
    priority: 'Critical' | 'High' | 'Medium' | 'Low';
    segment: string;
    status: 'Planned' | 'In Progress' | 'Considering' | 'Declined';
}

export interface CustomerInsightsReport {
    generatedAt: string;
    companyName: string;
    industry: string;
    dataSource: 'ai_analysis' | 'industry_data' | 'estimated';
    dataSources: string[];

    // Tier 1: Who are they?
    idealCustomerProfile: IdealCustomerProfile;
    userPersonas: UserPersona[];

    // Tier 2: Why they buy?
    painPoints: PainPoint[];
    desiredOutcomes: Array<{ outcome: string; metric: string; timeframe: string }>;
    triggerEvents: TriggerEvent[];

    // Tier 3: How they buy?
    buyingProcess: BuyingStage[];
    purchaseBarriers: PurchaseBarrier[];
    buyingCommittee: {
        avgSize: number;
        typicalCycle: string;
        budgetHolder: string;
    };

    // Tier 4: Voice of Customer
    commonObjections: CustomerObjection[];
    sentimentAnalysis: {
        overall: number;
        positive: number;
        neutral: number;
        negative: number;
        trend: 'Improving' | 'Stable' | 'Declining';
        topPositiveThemes: string[];
        topNegativeThemes: string[];
    };
    featureRequests: FeatureRequest[];
    npsScore: number;

    // Summary
    executiveSummary: {
        overview: string;
        keyInsights: string[];
        recommendations: string[];
    };
}

// ============================================================================
// GEMINI AI CLIENT
// ============================================================================

let geminiInstance: GoogleGenAI | null = null;

function getGemini(): GoogleGenAI | null {
    if (geminiInstance) return geminiInstance;
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
        console.warn('⚠️ GEMINI_API_KEY not set — customer insights will use fallback data');
        return null;
    }
    geminiInstance = new GoogleGenAI({ apiKey: key });
    return geminiInstance;
}

// ============================================================================
// CACHE (30-minute TTL)
// ============================================================================

const insightsCache = new Map<string, { data: any; ts: number }>();
const CACHE_TTL = 30 * 60 * 1000;

function getCached(key: string): any | null {
    const entry = insightsCache.get(key);
    if (entry && Date.now() - entry.ts < CACHE_TTL) return entry.data;
    if (entry) insightsCache.delete(key);
    return null;
}

function setCache(key: string, data: any): void {
    insightsCache.set(key, { data, ts: Date.now() });
}

// ============================================================================
// INDUSTRY CONTEXT FROM REAL DATABASE
// ============================================================================

interface IndustryContext {
    industry: string;
    totalCompanies: number;
    avgSize: string;
    commonLocations: string[];
    sampleCompanyNames: string[];
    companySizes: string[];
}

async function buildIndustryContext(industry: string, companyName: string): Promise<IndustryContext> {
    try {
        const allCompanies = await loadAllCompanies();
        const industryCompanies = allCompanies.filter(c =>
            c.industry?.toLowerCase() === industry.toLowerCase()
        );

        const locations = new Map<string, number>();
        const sizes = new Map<string, number>();
        for (const c of industryCompanies) {
            if (c.address) {
                const city = c.address.split(',').pop()?.trim() || c.address;
                locations.set(city, (locations.get(city) || 0) + 1);
            }
            if (c.size) sizes.set(c.size, (sizes.get(c.size) || 0) + 1);
        }

        const topLocations = [...locations.entries()]
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5)
            .map(([loc]) => loc);

        const topSizes = [...sizes.entries()]
            .sort((a, b) => b[1] - a[1])
            .slice(0, 4)
            .map(([s]) => s);

        const sampleNames = industryCompanies
            .filter(c => c.name.toLowerCase() !== companyName.toLowerCase())
            .slice(0, 10)
            .map(c => c.name);

        return {
            industry,
            totalCompanies: industryCompanies.length,
            avgSize: topSizes[0] || 'Unknown',
            commonLocations: topLocations.length > 0 ? topLocations : ['Ho Chi Minh City', 'Hanoi'],
            sampleCompanyNames: sampleNames,
            companySizes: topSizes
        };
    } catch {
        return {
            industry,
            totalCompanies: 0,
            avgSize: 'Unknown',
            commonLocations: ['Ho Chi Minh City', 'Hanoi'],
            sampleCompanyNames: [],
            companySizes: []
        };
    }
}

// ============================================================================
// GEMINI AI ANALYSIS
// ============================================================================

async function analyzeWithGemini(
    companyName: string,
    industry: string,
    products: string,
    targetMarket: string,
    companyData: NormalizedCompany | null,
    industryCtx: IndustryContext
): Promise<any | null> {
    const ai = getGemini();
    if (!ai) return null;

    const cacheKey = `insights:${companyName}:${industry}`.toLowerCase();
    const cached = getCached(cacheKey);
    if (cached) {
        console.log(`   📦 Cache hit for customer insights: ${companyName}`);
        return cached;
    }

    const companyContext = companyData
        ? `Company info from database:
  - Name: ${companyData.name}
  - Industry: ${companyData.industry}
  - Products/Services: ${companyData.products || products || 'N/A'}
  - Description: ${companyData.intro || 'N/A'}
  - Location: ${companyData.address || 'Vietnam'}
  - Size: ${companyData.size || 'Unknown'}
  - Website: ${companyData.website || 'N/A'}`
        : `Company: ${companyName}
  - Industry: ${industry}
  - Products: ${products || 'N/A'}
  - Market: ${targetMarket}`;

    const industryInfo = industryCtx.totalCompanies > 0
        ? `Industry context from our database of ${industryCtx.totalCompanies} ${industry} companies in Vietnam:
  - Common locations: ${industryCtx.commonLocations.join(', ')}
  - Company sizes: ${industryCtx.companySizes.join(', ')}
  - Sample companies: ${industryCtx.sampleCompanyNames.slice(0, 5).join(', ')}`
        : `Industry: ${industry} in Vietnam`;

    const prompt = `You are a B2B customer insights expert specializing in the Vietnamese market.
Analyze the potential customers of this company and generate a comprehensive customer insights report.

${companyContext}

${industryInfo}

Target Market: ${targetMarket}

Return ONLY valid JSON with this EXACT structure (use English for all text content):
{
  "idealCustomerProfile": {
    "firmographics": {
      "companySize": ["SME (50-200)", "Mid-Market (200-1000)"],
      "industries": ["industry1", "industry2", "industry3", "industry4"],
      "regions": ["region1", "region2"],
      "annualRevenue": "revenue range",
      "employeeCount": "employee range",
      "techMaturity": "Early Adopter" or "Mainstream" or "Laggard"
    },
    "decisionMakers": [
      {
        "title": "job title",
        "role": "Economic Buyer" or "Technical Buyer" or "User Buyer" or "Champion",
        "concerns": ["concern1", "concern2", "concern3"],
        "successMetrics": ["metric1", "metric2", "metric3"]
      }
    ],
    "keyInfluencers": [
      {"title": "title", "influence": "High" or "Medium" or "Low", "focus": "focus area"}
    ]
  },
  "userPersonas": [
    {
      "name": "name with alliterative role prefix",
      "title": "job title",
      "avatar": "emoji",
      "age": "age range",
      "background": "professional background",
      "goals": ["goal1", "goal2", "goal3"],
      "frustrations": ["frustration1", "frustration2", "frustration3"],
      "preferredChannels": ["channel1", "channel2", "channel3"],
      "quote": "characteristic quote",
      "dayInLife": ["activity1", "activity2", "activity3"],
      "techStack": ["tool1", "tool2", "tool3"]
    }
  ],
  "painPoints": [
    {
      "category": "category",
      "pain": "specific pain point relevant to ${companyName}'s customers",
      "severity": "Critical" or "High" or "Medium" or "Low",
      "frequency": "how often",
      "currentSolution": "what they do now",
      "costOfInaction": "cost of not solving"
    }
  ],
  "desiredOutcomes": [
    {"outcome": "specific outcome", "metric": "measurable metric", "timeframe": "timeframe"}
  ],
  "triggerEvents": [
    {
      "event": "trigger event",
      "urgency": "Immediate" or "Short-term" or "Long-term",
      "likelihood": 70,
      "signals": ["signal1", "signal2"],
      "approach": "sales approach"
    }
  ],
  "buyingProcess": [
    {
      "stage": "stage name",
      "description": "stage description",
      "duration": "duration",
      "activities": ["activity1", "activity2"],
      "contentNeeded": ["content1", "content2"],
      "objections": ["objection1"],
      "successCriteria": "success criteria"
    }
  ],
  "purchaseBarriers": [
    {
      "barrier": "barrier description",
      "category": "Price" or "Trust" or "Complexity" or "Timing" or "Politics" or "Competition",
      "severity": "High" or "Medium" or "Low",
      "overcomingStrategy": "overcoming strategy",
      "proofPoints": ["proof1", "proof2"]
    }
  ],
  "buyingCommittee": {
    "avgSize": 4,
    "typicalCycle": "X days",
    "budgetHolder": "job title"
  },
  "commonObjections": [
    {
      "objection": "objection statement",
      "frequency": 75,
      "category": "Price or Usability or Competition or Timing or Implementation",
      "response": "detailed response",
      "proofPoints": ["proof1", "proof2"]
    }
  ],
  "sentimentAnalysis": {
    "overall": 7.5,
    "positive": 55,
    "neutral": 30,
    "negative": 15,
    "trend": "Improving" or "Stable" or "Declining",
    "topPositiveThemes": ["theme1", "theme2", "theme3"],
    "topNegativeThemes": ["theme1", "theme2"]
  },
  "featureRequests": [
    {
      "feature": "feature name",
      "votes": 150,
      "priority": "Critical" or "High" or "Medium" or "Low",
      "segment": "segment",
      "status": "Planned" or "In Progress" or "Considering" or "Declined"
    }
  ],
  "npsScore": 45,
  "executiveSummary": {
    "overview": "2-3 sentence overview about ${companyName}'s customer landscape",
    "keyInsights": ["insight1", "insight2", "insight3", "insight4", "insight5"],
    "recommendations": ["recommendation1", "recommendation2", "recommendation3"]
  }
}

IMPORTANT RULES:
- Generate 3 personas specific to ${companyName}'s likely customers in Vietnam
- Generate 4-6 pain points specific to what ${companyName} solves
- Generate 5 buying process stages specific to ${industry} in Vietnam
- Generate 4-5 purchase barriers relevant to Vietnam B2B
- Generate 5-6 common objections with realistic frequencies (50-90)
- Sentiment: reflect typical ${industry} B2B landscape based on your knowledge (not real survey data — note this)
- NPS: industry benchmarks for ${industry} in Vietnam (30-60 range)
- Feature requests: realistic for ${companyName}'s product type, votes 50-250
- All text content in English
- Be specific to ${companyName} — do NOT use generic templates
- 3-4 decision makers, 2-3 key influencers`;

    const MAX_RETRIES = 2;
    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
            const { generateWithFallback } = await import('./geminiHelper');
            const result = await generateWithFallback({
                contents: prompt,
                config: {
                    temperature: 0.4,
                    maxOutputTokens: 4000,
                    tools: [{ googleSearch: {} }],
                }
            });

            const text = result.text || '';
            const jsonMatch = text.match(/\{[\s\S]*\}/);
            if (!jsonMatch) {
                console.warn(`   ⚠️ Gemini returned non-JSON for customer insights`);
                return null;
            }

            const parsed = JSON.parse(jsonMatch[0]);
            setCache(cacheKey, parsed);
            console.log(`   🤖 AI customer insights generated for: ${companyName} (via ${result.model})`);
            return parsed;
        } catch (err: any) {
            const is429 = err?.status === 429 || err?.message?.includes('429') || err?.message?.includes('quota');
            if (is429 && attempt < MAX_RETRIES) {
                const delay = (attempt + 1) * 5000;
                console.warn(`   ⏳ Gemini rate-limited, retry ${attempt + 1}/${MAX_RETRIES} in ${delay / 1000}s...`);
                await new Promise(r => setTimeout(r, delay));
                continue;
            }
            console.error(`   ❌ Gemini customer insights error:`, err?.message || err);
            return null;
        }
    }
    return null;
}

// ============================================================================
// FALLBACK BUILDERS (when AI is unavailable)
// ============================================================================

function buildFallbackICP(industry: string, ctx: IndustryContext): IdealCustomerProfile {
    const industryTargets: Record<string, string[]> = {
        'Technology': ['E-commerce', 'Fintech', 'Healthcare', 'Education', 'Manufacturing'],
        'Finance': ['Banking', 'Insurance', 'Investment', 'Payment', 'Lending'],
        'Retail': ['FMCG', 'Fashion', 'Electronics', 'Food & Beverage', 'Home'],
        'Education': ['K-12', 'University', 'EdTech', 'Corporate Training', 'Online Learning'],
        'Healthcare': ['Hospital', 'Clinic', 'Pharma', 'Medical Device', 'Telehealth'],
    };

    return {
        firmographics: {
            companySize: ['SME (50-200)', 'Mid-Market (200-1000)'],
            industries: industryTargets[industry] || ['SME', 'Enterprise', 'Startup'],
            regions: ctx.commonLocations.length > 0 ? ctx.commonLocations.slice(0, 3) : ['Ho Chi Minh City', 'Hanoi', 'Da Nang'],
            annualRevenue: 'No specific data available',
            employeeCount: ctx.avgSize !== 'Unknown' ? ctx.avgSize : '50-500',
            techMaturity: 'Mainstream'
        },
        decisionMakers: [
            { title: 'CEO / Founder', role: 'Economic Buyer', concerns: ['ROI', 'Total cost', 'Risk'], successMetrics: ['Revenue growth', 'Cost reduction'] },
            { title: 'CTO / IT Director', role: 'Technical Buyer', concerns: ['System integration', 'Security', 'Scalability'], successMetrics: ['Uptime', 'System performance'] },
            { title: 'Operations Manager', role: 'User Buyer', concerns: ['Ease of use', 'Daily workflows'], successMetrics: ['Time savings', 'Adoption rate'] },
        ],
        keyInfluencers: [
            { title: 'End Users', influence: 'High', focus: 'Daily user experience' },
            { title: 'IT Team', influence: 'Medium', focus: 'Integration and maintenance' },
        ]
    };
}

function buildFallbackPersonas(industry: string, companyName: string): UserPersona[] {
    return [
        {
            name: 'Director Giang',
            title: 'CEO / Founder',
            avatar: '👔',
            age: '35-50',
            background: `Business leader in ${industry}, focused on growth and efficiency`,
            goals: ['Market expansion', 'Optimize operational costs', 'Revenue growth'],
            frustrations: ['Lack of data for decision-making', 'Manual processes', 'Difficulty finding talent'],
            preferredChannels: ['LinkedIn', 'Industry seminars', 'Peer referral'],
            quote: '"I need a solution that delivers clearly measurable ROI."',
            dayInLife: ['Strategy meetings', 'Review KPI', 'Partner meetings', 'Vendor evaluation'],
            techStack: ['Email', 'Slack', 'Google Workspace', 'ERP']
        },
        {
            name: 'Engineer Khoa',
            title: 'CTO / Technical Lead',
            avatar: '👨‍💻',
            age: '30-40',
            background: `Technical expert in ${industry}, focused on systems and technology`,
            goals: ['Build stable systems', 'Reduce technical debt', 'Adopt new technologies'],
            frustrations: ['Legacy systems', 'Poor documentation', 'Vendor lock-in'],
            preferredChannels: ['GitHub', 'Tech blogs', 'Stack Overflow', 'Meetups'],
            quote: '"Production-ready, not just a demo."',
            dayInLife: ['Code review', 'Architecture planning', 'Team standup', 'Research'],
            techStack: ['AWS/GCP', 'Docker', 'CI/CD', 'Monitoring tools']
        },
        {
            name: 'Manager Mai',
            title: 'Operations / Product Manager',
            avatar: '👩‍💼',
            age: '28-38',
            background: `Operations manager in ${industry}, data-driven`,
            goals: ['Increase team productivity', 'Improve customer experience', 'Reduce processing time'],
            frustrations: ['Data silos', 'Manual processes', 'Lack of automation'],
            preferredChannels: ['LinkedIn', 'Product Hunt', 'Industry events'],
            quote: '"Show me the data."',
            dayInLife: ['Sprint planning', 'KPI tracking', 'Process optimization', 'Stakeholder meetings'],
            techStack: ['Jira', 'Notion', 'Analytics tools', 'Slack']
        }
    ];
}

function buildFallbackPainPoints(industry: string, companyName: string): PainPoint[] {
    return [
        {
            category: 'Productivity',
            pain: `Potential customers of ${companyName} spend too much time on manual processes`,
            severity: 'High',
            frequency: 'Daily',
            currentSolution: 'Manual processing or Excel',
            costOfInaction: 'High labor costs, frequent errors'
        },
        {
            category: 'Data',
            pain: 'No unified data source (single source of truth)',
            severity: 'High',
            frequency: 'Weekly',
            currentSolution: 'Manual aggregation from multiple sources',
            costOfInaction: 'Poor decisions, wasted resources'
        },
        {
            category: 'Growth',
            pain: 'Difficulty scaling as customers/transactions increase',
            severity: 'Critical',
            frequency: 'During rapid growth',
            currentSolution: 'Hiring more staff',
            costOfInaction: 'Lost opportunities, revenue capped'
        },
        {
            category: 'Competition',
            pain: 'Competitors are digitizing faster',
            severity: 'Medium',
            frequency: 'Continuous',
            currentSolution: 'Manual monitoring',
            costOfInaction: 'Losing market share'
        }
    ];
}

function buildFallbackReport(
    companyName: string,
    industry: string,
    _products: string,
    targetMarket: string,
    ctx: IndustryContext
): CustomerInsightsReport {
    const icp = buildFallbackICP(industry, ctx);
    const personas = buildFallbackPersonas(industry, companyName);
    const painPoints = buildFallbackPainPoints(industry, companyName);

    return {
        generatedAt: new Date().toISOString(),
        companyName,
        industry,
        dataSource: 'estimated',
        dataSources: [
            ctx.totalCompanies > 0 ? `VICO Company Database (${ctx.totalCompanies} ${industry} companies)` : 'Industry templates',
            'Fallback mode — Gemini AI unavailable'
        ],

        idealCustomerProfile: icp,
        userPersonas: personas,

        painPoints,
        desiredOutcomes: [
            { outcome: 'Reduce operational costs', metric: 'Needs specific measurement', timeframe: '6 months' },
            { outcome: 'Increase employee productivity', metric: 'Needs specific measurement', timeframe: '3 months' },
            { outcome: 'Improve customer experience', metric: 'Needs specific measurement', timeframe: '12 months' },
        ],
        triggerEvents: [
            { event: 'Rapid growth', urgency: 'Immediate', likelihood: 75, signals: ['Hiring surge', 'Revenue increase'], approach: 'Direct outbound' },
            { event: 'Digital transformation', urgency: 'Short-term', likelihood: 65, signals: ['New IT lead hired', 'IT budget increased'], approach: 'Content marketing' },
            { event: 'Leadership change', urgency: 'Short-term', likelihood: 55, signals: ['New CEO/CTO', 'Restructuring'], approach: 'Executive outreach' },
        ],

        buyingProcess: [
            {
                stage: '1. Problem awareness',
                description: 'Customer realizes they need a new solution',
                duration: '2-4 weeks',
                activities: ['Reading industry reports', 'Internal discussions'],
                contentNeeded: ['Blog posts', 'Industry reports'],
                objections: ['Not a priority yet'],
                successCriteria: 'Agreement that this is a problem worth solving'
            },
            {
                stage: '2. Solution search',
                description: 'Comparing available options',
                duration: '2-6 weeks',
                activities: ['Google search', 'Demo request', 'Asking peers'],
                contentNeeded: ['Product comparison', 'Demo', 'Free trial'],
                objections: ['Too many options'],
                successCriteria: 'Shortlist 2-3 vendors'
            },
            {
                stage: '3. Detailed evaluation',
                description: 'POC and technical assessment',
                duration: '2-4 weeks',
                activities: ['POC', 'Reference calls', 'Negotiation'],
                contentNeeded: ['Technical docs', 'Customer references'],
                objections: ['Missing features', 'High price'],
                successCriteria: 'Select preferred vendor'
            },
            {
                stage: '4. Purchase decision',
                description: 'Approval and contract signing',
                duration: '1-4 weeks',
                activities: ['Final negotiation', 'Legal review', 'Budget approval'],
                contentNeeded: ['Proposal', 'Contract', 'SLA'],
                objections: ['Budget freeze', 'Need more approvals'],
                successCriteria: 'Contract signed'
            },
            {
                stage: '5. Implementation & Adoption',
                description: 'Onboarding and starting usage',
                duration: '4-12 weeks',
                activities: ['Implementation', 'Training', 'Go-live'],
                contentNeeded: ['Onboarding guide', 'Training videos'],
                objections: ['Too complex', 'Staff resistant to change'],
                successCriteria: 'Active usage'
            }
        ],
        purchaseBarriers: [
            { barrier: 'Limited budget', category: 'Price', severity: 'High', overcomingStrategy: 'Flexible payment, ROI calculator, pilot program', proofPoints: ['ROI case study', 'Payment plan options'] },
            { barrier: 'Fear of complex implementation', category: 'Complexity', severity: 'High', overcomingStrategy: 'Pre-built templates, dedicated CSM', proofPoints: ['2-week implementation avg', 'Customer success stories'] },
            { barrier: 'Already using another solution', category: 'Competition', severity: 'Medium', overcomingStrategy: 'Free migration, parallel running', proofPoints: ['Migration guide', 'Zero-downtime guarantee'] },
            { barrier: 'Internal politics', category: 'Politics', severity: 'Medium', overcomingStrategy: 'Stakeholder-specific materials', proofPoints: ['Role-based value props', 'Champion toolkit'] },
        ],
        buyingCommittee: {
            avgSize: 4,
            typicalCycle: '60 days',
            budgetHolder: 'CEO / CFO'
        },

        commonObjections: [
            { objection: 'Your price is higher than the competition', frequency: 80, category: 'Price', response: 'Total Cost of Ownership is lower when fully calculated', proofPoints: ['TCO comparison', 'ROI calculator'] },
            { objection: 'We are already using another solution', frequency: 65, category: 'Competition', response: 'Free migration support with zero downtime', proofPoints: ['Migration guide', 'Switch case studies'] },
            { objection: 'Need to consult additional stakeholders', frequency: 60, category: 'Decision Process', response: 'Prepare materials for each stakeholder', proofPoints: ['Stakeholder decks', 'Executive summary'] },
            { objection: 'Now is not the right time', frequency: 55, category: 'Timing', response: 'Flexible payment, cost of delay analysis', proofPoints: ['Cost of delay calculator', 'Quick start program'] },
        ],
        sentimentAnalysis: {
            overall: 0,
            positive: 0,
            neutral: 0,
            negative: 0,
            trend: 'Stable',
            topPositiveThemes: ['No real sentiment data available'],
            topNegativeThemes: ['No real sentiment data available']
        },
        featureRequests: [],
        npsScore: 0,

        executiveSummary: {
            overview: `Customer insights analysis for ${companyName} in the ${industry} industry in ${targetMarket}. ` +
                (ctx.totalCompanies > 0
                    ? `VICO database has ${ctx.totalCompanies} ${industry} companies. `
                    : '') +
                `Note: AI unavailable so data is based on industry benchmarks, not specific analysis.`,
            keyInsights: [
                `ICP: ${icp.firmographics.industries.slice(0, 3).join(', ')}`,
                `Key pain point: ${painPoints[0]?.pain || 'Operational efficiency'}`,
                `Decision maker: ${icp.decisionMakers[0]?.title || 'CEO'}`,
                `Sentiment/NPS data: not available — requires real survey data`,
            ],
            recommendations: [
                `Focus on trigger event "Rapid growth" to reach customers`,
                `Build content addressing pain point "${painPoints[0]?.pain || 'efficiency'}"`,
                `Collect real feedback for accurate NPS and sentiment data`,
            ]
        }
    };
}

// ============================================================================
// MAIN EXPORT
// ============================================================================

export async function generateCustomerInsights(params: {
    companyName: string;
    industry?: string;
    products?: string;
    targetMarket?: string;
}): Promise<CustomerInsightsReport> {
    const { companyName, industry = 'Technology', products = '', targetMarket = 'Vietnam' } = params;

    console.log(`🎯 Customer Insights Request: ${companyName} (${industry})`);

    // 1. Find company in database
    let companyData: NormalizedCompany | null = null;
    try {
        const allCompanies = await loadAllCompanies();
        companyData = allCompanies.find(c =>
            c.name.toLowerCase().includes(companyName.toLowerCase()) ||
            companyName.toLowerCase().includes(c.name.toLowerCase())
        ) || null;
        if (companyData) {
            console.log(`   📊 Found company in database: ${companyData.name} (${companyData.industry})`);
        }
    } catch (err) {
        console.warn('   ⚠️ Could not load company database');
    }

    const detectedIndustry = companyData?.industry || industry;

    // 2. Build industry context from real database
    const industryCtx = await buildIndustryContext(detectedIndustry, companyName);
    console.log(`   📈 Industry context: ${industryCtx.totalCompanies} companies in ${detectedIndustry}`);

    // 3. Try AI analysis
    const aiInsights = await analyzeWithGemini(
        companyName, detectedIndustry, products, targetMarket, companyData, industryCtx
    );

    if (aiInsights) {
        // Successfully generated AI insights — map to typed report
        const report: CustomerInsightsReport = {
            generatedAt: new Date().toISOString(),
            companyName,
            industry: detectedIndustry,
            dataSource: 'ai_analysis',
            dataSources: [
                companyData ? 'VICO Company Database' : 'User input',
                'Gemini 2.0 Flash AI Analysis',
                industryCtx.totalCompanies > 0 ? `Industry data (${industryCtx.totalCompanies} companies)` : ''
            ].filter(Boolean),

            idealCustomerProfile: {
                firmographics: {
                    ...aiInsights.idealCustomerProfile.firmographics,
                    techMaturity: (aiInsights.idealCustomerProfile.firmographics.techMaturity as any) || 'Mainstream'
                },
                decisionMakers: (aiInsights.idealCustomerProfile.decisionMakers || []).map((dm: any) => ({
                    ...dm,
                    role: dm.role as any || 'Champion'
                })),
                keyInfluencers: (aiInsights.idealCustomerProfile.keyInfluencers || []).map((ki: any) => ({
                    ...ki,
                    influence: ki.influence as any || 'Medium'
                }))
            },
            userPersonas: aiInsights.userPersonas || [],

            painPoints: (aiInsights.painPoints || []).map((pp: any) => ({
                ...pp,
                severity: pp.severity as any || 'Medium'
            })),
            desiredOutcomes: aiInsights.desiredOutcomes || [],
            triggerEvents: (aiInsights.triggerEvents || []).map((te: any) => ({
                ...te,
                urgency: te.urgency as any || 'Short-term'
            })),

            buyingProcess: aiInsights.buyingProcess || [],
            purchaseBarriers: (aiInsights.purchaseBarriers || []).map((pb: any) => ({
                ...pb,
                category: pb.category as any || 'Complexity',
                severity: pb.severity as any || 'Medium'
            })),
            buyingCommittee: aiInsights.buyingCommittee || { avgSize: 4, typicalCycle: '60 days', budgetHolder: 'CEO' },

            commonObjections: aiInsights.commonObjections || [],
            sentimentAnalysis: {
                overall: aiInsights.sentimentAnalysis?.overall || 0,
                positive: aiInsights.sentimentAnalysis?.positive || 0,
                neutral: aiInsights.sentimentAnalysis?.neutral || 0,
                negative: aiInsights.sentimentAnalysis?.negative || 0,
                trend: (aiInsights.sentimentAnalysis?.trend as any) || 'Stable',
                topPositiveThemes: aiInsights.sentimentAnalysis?.topPositiveThemes || [],
                topNegativeThemes: aiInsights.sentimentAnalysis?.topNegativeThemes || []
            },
            featureRequests: (aiInsights.featureRequests || []).map((fr: any) => ({
                ...fr,
                priority: fr.priority as any || 'Medium',
                status: fr.status as any || 'Considering'
            })),
            npsScore: aiInsights.npsScore || 0,

            executiveSummary: aiInsights.executiveSummary || {
                overview: `AI analysis for ${companyName}`,
                keyInsights: [],
                recommendations: []
            }
        };

        console.log(`✅ Customer Insights generated via AI for ${companyName}`);
        return report;
    }

    // 4. Fallback when AI unavailable
    console.log(`   ⚠️ Using fallback insights for ${companyName} (AI unavailable)`);
    return buildFallbackReport(companyName, detectedIndustry, products, targetMarket, industryCtx);
}

export default generateCustomerInsights;
