/**
 * 🎯 Customer Insights Service — AI-Powered (Gemini 2.0 Flash)
 * 
 * Generates customer insights using:
 * 1. Real company data from CSV/database (name, industry, products, location, size)
 * 2. Gemini AI for deep customer understanding (personas, pain points, buying process)
 * 3. Clearly labeled data provenance — no fabricated statistics presented as fact
 * 
 * Data provenance:
 * - "ai_analysis"     = generated by Gemini based on company + industry context
 * - "industry_data"   = derived from real company database industry stats
 * - "estimated"       = fallback when AI unavailable
 */

import { GoogleGenAI } from '@google/genai';
import { loadAllCompanies, NormalizedCompany } from './competitorEngine';

// ============================================================================
// TYPES (backward-compatible with frontend CustomerInsightsPage.tsx)
// ============================================================================

export interface IdealCustomerProfile {
    firmographics: {
        companySize: string[];
        industries: string[];
        regions: string[];
        annualRevenue: string;
        employeeCount: string;
        techMaturity: 'Early Adopter' | 'Mainstream' | 'Laggard';
    };
    decisionMakers: Array<{
        title: string;
        role: 'Economic Buyer' | 'Technical Buyer' | 'User Buyer' | 'Champion';
        concerns: string[];
        successMetrics: string[];
    }>;
    keyInfluencers: Array<{
        title: string;
        influence: 'High' | 'Medium' | 'Low';
        focus: string;
    }>;
}

export interface UserPersona {
    name: string;
    title: string;
    avatar: string;
    age: string;
    background: string;
    goals: string[];
    frustrations: string[];
    preferredChannels: string[];
    quote: string;
    dayInLife: string[];
    techStack: string[];
}

export interface PainPoint {
    category: string;
    pain: string;
    severity: 'Critical' | 'High' | 'Medium' | 'Low';
    frequency: string;
    currentSolution: string;
    costOfInaction: string;
}

export interface TriggerEvent {
    event: string;
    urgency: 'Immediate' | 'Short-term' | 'Long-term';
    likelihood: number;
    signals: string[];
    approach: string;
}

export interface BuyingStage {
    stage: string;
    description: string;
    duration: string;
    activities: string[];
    contentNeeded: string[];
    objections: string[];
    successCriteria: string;
}

export interface PurchaseBarrier {
    barrier: string;
    category: 'Price' | 'Trust' | 'Complexity' | 'Timing' | 'Politics' | 'Competition';
    severity: 'High' | 'Medium' | 'Low';
    overcomingStrategy: string;
    proofPoints: string[];
}

export interface CustomerObjection {
    objection: string;
    frequency: number;
    category: string;
    response: string;
    proofPoints: string[];
}

export interface FeatureRequest {
    feature: string;
    votes: number;
    priority: 'Critical' | 'High' | 'Medium' | 'Low';
    segment: string;
    status: 'Planned' | 'In Progress' | 'Considering' | 'Declined';
}

export interface CustomerInsightsReport {
    generatedAt: string;
    companyName: string;
    industry: string;
    dataSource: 'ai_analysis' | 'industry_data' | 'estimated';
    dataSources: string[];

    // Tier 1: Who are they?
    idealCustomerProfile: IdealCustomerProfile;
    userPersonas: UserPersona[];

    // Tier 2: Why they buy?
    painPoints: PainPoint[];
    desiredOutcomes: Array<{ outcome: string; metric: string; timeframe: string }>;
    triggerEvents: TriggerEvent[];

    // Tier 3: How they buy?
    buyingProcess: BuyingStage[];
    purchaseBarriers: PurchaseBarrier[];
    buyingCommittee: {
        avgSize: number;
        typicalCycle: string;
        budgetHolder: string;
    };

    // Tier 4: Voice of Customer
    commonObjections: CustomerObjection[];
    sentimentAnalysis: {
        overall: number;
        positive: number;
        neutral: number;
        negative: number;
        trend: 'Improving' | 'Stable' | 'Declining';
        topPositiveThemes: string[];
        topNegativeThemes: string[];
    };
    featureRequests: FeatureRequest[];
    npsScore: number;

    // Summary
    executiveSummary: {
        overview: string;
        keyInsights: string[];
        recommendations: string[];
    };
}

// ============================================================================
// GEMINI AI CLIENT
// ============================================================================

let geminiInstance: GoogleGenAI | null = null;

function getGemini(): GoogleGenAI | null {
    if (geminiInstance) return geminiInstance;
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
        console.warn('⚠️ GEMINI_API_KEY not set — customer insights will use fallback data');
        return null;
    }
    geminiInstance = new GoogleGenAI({ apiKey: key });
    return geminiInstance;
}

// ============================================================================
// CACHE (30-minute TTL)
// ============================================================================

const insightsCache = new Map<string, { data: any; ts: number }>();
const CACHE_TTL = 30 * 60 * 1000;

function getCached(key: string): any | null {
    const entry = insightsCache.get(key);
    if (entry && Date.now() - entry.ts < CACHE_TTL) return entry.data;
    if (entry) insightsCache.delete(key);
    return null;
}

function setCache(key: string, data: any): void {
    insightsCache.set(key, { data, ts: Date.now() });
}

// ============================================================================
// INDUSTRY CONTEXT FROM REAL DATABASE
// ============================================================================

interface IndustryContext {
    industry: string;
    totalCompanies: number;
    avgSize: string;
    commonLocations: string[];
    sampleCompanyNames: string[];
    companySizes: string[];
}

async function buildIndustryContext(industry: string, companyName: string): Promise<IndustryContext> {
    try {
        const allCompanies = await loadAllCompanies();
        const industryCompanies = allCompanies.filter(c =>
            c.industry?.toLowerCase() === industry.toLowerCase()
        );

        const locations = new Map<string, number>();
        const sizes = new Map<string, number>();
        for (const c of industryCompanies) {
            if (c.address) {
                const city = c.address.split(',').pop()?.trim() || c.address;
                locations.set(city, (locations.get(city) || 0) + 1);
            }
            if (c.size) sizes.set(c.size, (sizes.get(c.size) || 0) + 1);
        }

        const topLocations = [...locations.entries()]
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5)
            .map(([loc]) => loc);

        const topSizes = [...sizes.entries()]
            .sort((a, b) => b[1] - a[1])
            .slice(0, 4)
            .map(([s]) => s);

        const sampleNames = industryCompanies
            .filter(c => c.name.toLowerCase() !== companyName.toLowerCase())
            .slice(0, 10)
            .map(c => c.name);

        return {
            industry,
            totalCompanies: industryCompanies.length,
            avgSize: topSizes[0] || 'Unknown',
            commonLocations: topLocations.length > 0 ? topLocations : ['Ho Chi Minh City', 'Hanoi'],
            sampleCompanyNames: sampleNames,
            companySizes: topSizes
        };
    } catch {
        return {
            industry,
            totalCompanies: 0,
            avgSize: 'Unknown',
            commonLocations: ['Ho Chi Minh City', 'Hanoi'],
            sampleCompanyNames: [],
            companySizes: []
        };
    }
}

// ============================================================================
// GEMINI AI ANALYSIS
// ============================================================================

async function analyzeWithGemini(
    companyName: string,
    industry: string,
    products: string,
    targetMarket: string,
    companyData: NormalizedCompany | null,
    industryCtx: IndustryContext
): Promise<any | null> {
    const ai = getGemini();
    if (!ai) return null;

    const cacheKey = `insights:${companyName}:${industry}`.toLowerCase();
    const cached = getCached(cacheKey);
    if (cached) {
        console.log(`   📦 Cache hit for customer insights: ${companyName}`);
        return cached;
    }

    const companyContext = companyData
        ? `Company info from database:
  - Name: ${companyData.name}
  - Industry: ${companyData.industry}
  - Products/Services: ${companyData.products || products || 'N/A'}
  - Description: ${companyData.intro || 'N/A'}
  - Location: ${companyData.address || 'Vietnam'}
  - Size: ${companyData.size || 'Unknown'}
  - Website: ${companyData.website || 'N/A'}`
        : `Company: ${companyName}
  - Industry: ${industry}
  - Products: ${products || 'N/A'}
  - Market: ${targetMarket}`;

    const industryInfo = industryCtx.totalCompanies > 0
        ? `Industry context from our database of ${industryCtx.totalCompanies} ${industry} companies in Vietnam:
  - Common locations: ${industryCtx.commonLocations.join(', ')}
  - Company sizes: ${industryCtx.companySizes.join(', ')}
  - Sample companies: ${industryCtx.sampleCompanyNames.slice(0, 5).join(', ')}`
        : `Industry: ${industry} in Vietnam`;

    const prompt = `You are a B2B customer insights expert specializing in the Vietnamese market.
Analyze the potential customers of this company and generate a comprehensive customer insights report.

${companyContext}

${industryInfo}

Target Market: ${targetMarket}

Return ONLY valid JSON with this EXACT structure (use Vietnamese for all text content):
{
  "idealCustomerProfile": {
    "firmographics": {
      "companySize": ["SME (50-200)", "Mid-Market (200-1000)"],
      "industries": ["industry1", "industry2", "industry3", "industry4"],
      "regions": ["region1", "region2"],
      "annualRevenue": "revenue range",
      "employeeCount": "employee range",
      "techMaturity": "Early Adopter" or "Mainstream" or "Laggard"
    },
    "decisionMakers": [
      {
        "title": "job title",
        "role": "Economic Buyer" or "Technical Buyer" or "User Buyer" or "Champion",
        "concerns": ["concern1", "concern2", "concern3"],
        "successMetrics": ["metric1", "metric2", "metric3"]
      }
    ],
    "keyInfluencers": [
      {"title": "title", "influence": "High" or "Medium" or "Low", "focus": "focus area"}
    ]
  },
  "userPersonas": [
    {
      "name": "Vietnamese name with alliterative role prefix",
      "title": "job title",
      "avatar": "emoji",
      "age": "age range",
      "background": "background in Vietnamese",
      "goals": ["goal1", "goal2", "goal3"],
      "frustrations": ["frustration1", "frustration2", "frustration3"],
      "preferredChannels": ["channel1", "channel2", "channel3"],
      "quote": "characteristic quote in Vietnamese",
      "dayInLife": ["activity1", "activity2", "activity3"],
      "techStack": ["tool1", "tool2", "tool3"]
    }
  ],
  "painPoints": [
    {
      "category": "category",
      "pain": "specific pain point relevant to ${companyName}'s customers in Vietnamese",
      "severity": "Critical" or "High" or "Medium" or "Low",
      "frequency": "how often",
      "currentSolution": "what they do now",
      "costOfInaction": "cost of not solving"
    }
  ],
  "desiredOutcomes": [
    {"outcome": "outcome in Vietnamese", "metric": "measurable metric", "timeframe": "timeframe"}
  ],
  "triggerEvents": [
    {
      "event": "trigger event",
      "urgency": "Immediate" or "Short-term" or "Long-term",
      "likelihood": 70,
      "signals": ["signal1", "signal2"],
      "approach": "sales approach in Vietnamese"
    }
  ],
  "buyingProcess": [
    {
      "stage": "stage name in Vietnamese",
      "description": "description in Vietnamese",
      "duration": "duration",
      "activities": ["activity1", "activity2"],
      "contentNeeded": ["content1", "content2"],
      "objections": ["objection1"],
      "successCriteria": "criteria in Vietnamese"
    }
  ],
  "purchaseBarriers": [
    {
      "barrier": "barrier in Vietnamese",
      "category": "Price" or "Trust" or "Complexity" or "Timing" or "Politics" or "Competition",
      "severity": "High" or "Medium" or "Low",
      "overcomingStrategy": "strategy in Vietnamese",
      "proofPoints": ["proof1", "proof2"]
    }
  ],
  "buyingCommittee": {
    "avgSize": 4,
    "typicalCycle": "X ngày",
    "budgetHolder": "job title"
  },
  "commonObjections": [
    {
      "objection": "objection in Vietnamese",
      "frequency": 75,
      "category": "Price or Usability or Competition or Timing or Implementation",
      "response": "detailed response in Vietnamese",
      "proofPoints": ["proof1", "proof2"]
    }
  ],
  "sentimentAnalysis": {
    "overall": 7.5,
    "positive": 55,
    "neutral": 30,
    "negative": 15,
    "trend": "Improving" or "Stable" or "Declining",
    "topPositiveThemes": ["theme1", "theme2", "theme3"],
    "topNegativeThemes": ["theme1", "theme2"]
  },
  "featureRequests": [
    {
      "feature": "feature name",
      "votes": 150,
      "priority": "Critical" or "High" or "Medium" or "Low",
      "segment": "segment",
      "status": "Planned" or "In Progress" or "Considering" or "Declined"
    }
  ],
  "npsScore": 45,
  "executiveSummary": {
    "overview": "2-3 sentence overview in Vietnamese about ${companyName}'s customer landscape",
    "keyInsights": ["insight1", "insight2", "insight3", "insight4", "insight5"],
    "recommendations": ["recommendation1", "recommendation2", "recommendation3"]
  }
}

IMPORTANT RULES:
- Generate 3 personas specific to ${companyName}'s likely customers in Vietnam
- Generate 4-6 pain points specific to what ${companyName} solves
- Generate 5 buying process stages specific to ${industry} in Vietnam
- Generate 4-5 purchase barriers relevant to Vietnam B2B
- Generate 5-6 common objections with realistic frequencies (50-90)
- Sentiment: reflect typical ${industry} B2B landscape based on your knowledge (not real survey data — note this)
- NPS: industry benchmarks for ${industry} in Vietnam (30-60 range)
- Feature requests: realistic for ${companyName}'s product type, votes 50-250
- All text content in Vietnamese
- Be specific to ${companyName} — do NOT use generic templates
- 3-4 decision makers, 2-3 key influencers`;

    const MAX_RETRIES = 2;
    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
            const response = await ai.models.generateContent({
                model: 'gemini-2.0-flash',
                contents: prompt,
                config: {
                    temperature: 0.4,
                    maxOutputTokens: 4000,
                }
            });

            const text = response.text || '';
            const jsonMatch = text.match(/\{[\s\S]*\}/);
            if (!jsonMatch) {
                console.warn(`   ⚠️ Gemini returned non-JSON for customer insights`);
                return null;
            }

            const parsed = JSON.parse(jsonMatch[0]);
            setCache(cacheKey, parsed);
            console.log(`   🤖 AI customer insights generated for: ${companyName}`);
            return parsed;
        } catch (err: any) {
            const is429 = err?.status === 429 || err?.message?.includes('429') || err?.message?.includes('quota');
            if (is429 && attempt < MAX_RETRIES) {
                const delay = (attempt + 1) * 5000;
                console.warn(`   ⏳ Gemini rate-limited, retry ${attempt + 1}/${MAX_RETRIES} in ${delay / 1000}s...`);
                await new Promise(r => setTimeout(r, delay));
                continue;
            }
            console.error(`   ❌ Gemini customer insights error:`, err?.message || err);
            return null;
        }
    }
    return null;
}

// ============================================================================
// FALLBACK BUILDERS (when AI is unavailable)
// ============================================================================

function buildFallbackICP(industry: string, ctx: IndustryContext): IdealCustomerProfile {
    const industryTargets: Record<string, string[]> = {
        'Technology': ['E-commerce', 'Fintech', 'Healthcare', 'Education', 'Manufacturing'],
        'Finance': ['Banking', 'Insurance', 'Investment', 'Payment', 'Lending'],
        'Retail': ['FMCG', 'Fashion', 'Electronics', 'Food & Beverage', 'Home'],
        'Education': ['K-12', 'University', 'EdTech', 'Corporate Training', 'Online Learning'],
        'Healthcare': ['Hospital', 'Clinic', 'Pharma', 'Medical Device', 'Telehealth'],
    };

    return {
        firmographics: {
            companySize: ['SME (50-200)', 'Mid-Market (200-1000)'],
            industries: industryTargets[industry] || ['SME', 'Enterprise', 'Startup'],
            regions: ctx.commonLocations.length > 0 ? ctx.commonLocations.slice(0, 3) : ['Ho Chi Minh City', 'Hanoi', 'Da Nang'],
            annualRevenue: 'Chưa có dữ liệu cụ thể',
            employeeCount: ctx.avgSize !== 'Unknown' ? ctx.avgSize : '50-500',
            techMaturity: 'Mainstream'
        },
        decisionMakers: [
            { title: 'CEO / Founder', role: 'Economic Buyer', concerns: ['ROI', 'Chi phí tổng thể', 'Rủi ro'], successMetrics: ['Tăng trưởng doanh thu', 'Giảm chi phí'] },
            { title: 'CTO / IT Director', role: 'Technical Buyer', concerns: ['Tích hợp hệ thống', 'Bảo mật', 'Khả năng mở rộng'], successMetrics: ['Uptime', 'Hiệu suất hệ thống'] },
            { title: 'Operations Manager', role: 'User Buyer', concerns: ['Dễ sử dụng', 'Quy trình hàng ngày'], successMetrics: ['Tiết kiệm thời gian', 'Tỷ lệ adoption'] },
        ],
        keyInfluencers: [
            { title: 'End Users', influence: 'High', focus: 'Trải nghiệm sử dụng hàng ngày' },
            { title: 'IT Team', influence: 'Medium', focus: 'Tích hợp và bảo trì' },
        ]
    };
}

function buildFallbackPersonas(industry: string, companyName: string): UserPersona[] {
    return [
        {
            name: 'Giám đốc Giang',
            title: 'CEO / Founder',
            avatar: '👔',
            age: '35-50',
            background: `Lãnh đạo doanh nghiệp ${industry}, quan tâm đến tăng trưởng và hiệu quả`,
            goals: ['Mở rộng thị trường', 'Tối ưu chi phí vận hành', 'Tăng trưởng doanh thu'],
            frustrations: ['Thiếu dữ liệu để ra quyết định', 'Quy trình thủ công', 'Khó tìm talent'],
            preferredChannels: ['LinkedIn', 'Hội thảo ngành', 'Peer referral'],
            quote: '"Tôi cần giải pháp có thể đo lường được ROI rõ ràng."',
            dayInLife: ['Họp chiến lược', 'Review KPI', 'Gặp đối tác', 'Đánh giá vendor'],
            techStack: ['Email', 'Slack', 'Google Workspace', 'ERP']
        },
        {
            name: 'Kỹ thuật Khoa',
            title: 'CTO / Technical Lead',
            avatar: '👨‍💻',
            age: '30-40',
            background: `Chuyên gia kỹ thuật trong ngành ${industry}, tập trung vào hệ thống và công nghệ`,
            goals: ['Xây dựng hệ thống ổn định', 'Giảm technical debt', 'Áp dụng công nghệ mới'],
            frustrations: ['Legacy systems', 'Documentation kém', 'Vendor lock-in'],
            preferredChannels: ['GitHub', 'Tech blogs', 'Stack Overflow', 'Meetups'],
            quote: '"Production-ready, không phải demo."',
            dayInLife: ['Code review', 'Architecture planning', 'Team standup', 'Research'],
            techStack: ['AWS/GCP', 'Docker', 'CI/CD', 'Monitoring tools']
        },
        {
            name: 'Manager Mai',
            title: 'Operations / Product Manager',
            avatar: '👩‍💼',
            age: '28-38',
            background: `Quản lý vận hành trong ngành ${industry}, data-driven`,
            goals: ['Tăng hiệu suất team', 'Cải thiện trải nghiệm khách hàng', 'Giảm thời gian xử lý'],
            frustrations: ['Data silos', 'Quy trình thủ công', 'Thiếu automation'],
            preferredChannels: ['LinkedIn', 'Product Hunt', 'Industry events'],
            quote: '"Show me the data."',
            dayInLife: ['Sprint planning', 'KPI tracking', 'Process optimization', 'Stakeholder meetings'],
            techStack: ['Jira', 'Notion', 'Analytics tools', 'Slack']
        }
    ];
}

function buildFallbackPainPoints(industry: string, companyName: string): PainPoint[] {
    return [
        {
            category: 'Hiệu suất',
            pain: `Khách hàng tiềm năng của ${companyName} mất nhiều thời gian cho quy trình thủ công`,
            severity: 'High',
            frequency: 'Hàng ngày',
            currentSolution: 'Xử lý thủ công hoặc Excel',
            costOfInaction: 'Chi phí nhân công cao, sai sót nhiều'
        },
        {
            category: 'Dữ liệu',
            pain: 'Không có nguồn dữ liệu thống nhất (single source of truth)',
            severity: 'High',
            frequency: 'Hàng tuần',
            currentSolution: 'Tổng hợp thủ công từ nhiều nguồn',
            costOfInaction: 'Ra quyết định sai, lãng phí nguồn lực'
        },
        {
            category: 'Tăng trưởng',
            pain: 'Khó scale khi lượng khách hàng/giao dịch tăng',
            severity: 'Critical',
            frequency: 'Khi tăng trưởng nhanh',
            currentSolution: 'Thuê thêm nhân sự',
            costOfInaction: 'Mất cơ hội, revenue bị giới hạn'
        },
        {
            category: 'Cạnh tranh',
            pain: 'Đối thủ đang chuyển đổi số nhanh hơn',
            severity: 'Medium',
            frequency: 'Liên tục',
            currentSolution: 'Theo dõi thủ công',
            costOfInaction: 'Mất thị phần'
        }
    ];
}

function buildFallbackReport(
    companyName: string,
    industry: string,
    _products: string,
    targetMarket: string,
    ctx: IndustryContext
): CustomerInsightsReport {
    const icp = buildFallbackICP(industry, ctx);
    const personas = buildFallbackPersonas(industry, companyName);
    const painPoints = buildFallbackPainPoints(industry, companyName);

    return {
        generatedAt: new Date().toISOString(),
        companyName,
        industry,
        dataSource: 'estimated',
        dataSources: [
            ctx.totalCompanies > 0 ? `VICO Company Database (${ctx.totalCompanies} ${industry} companies)` : 'Industry templates',
            'Fallback mode — Gemini AI unavailable'
        ],

        idealCustomerProfile: icp,
        userPersonas: personas,

        painPoints,
        desiredOutcomes: [
            { outcome: 'Giảm chi phí vận hành', metric: 'Cần đo lường cụ thể', timeframe: '6 tháng' },
            { outcome: 'Tăng hiệu suất nhân viên', metric: 'Cần đo lường cụ thể', timeframe: '3 tháng' },
            { outcome: 'Cải thiện trải nghiệm khách hàng', metric: 'Cần đo lường cụ thể', timeframe: '12 tháng' },
        ],
        triggerEvents: [
            { event: 'Tăng trưởng nhanh', urgency: 'Immediate', likelihood: 75, signals: ['Tuyển dụng nhiều', 'Revenue tăng'], approach: 'Outbound trực tiếp' },
            { event: 'Chuyển đổi số', urgency: 'Short-term', likelihood: 65, signals: ['Tuyển IT lead mới', 'Budget IT tăng'], approach: 'Content marketing' },
            { event: 'Thay đổi lãnh đạo', urgency: 'Short-term', likelihood: 55, signals: ['CEO/CTO mới', 'Restructuring'], approach: 'Executive outreach' },
        ],

        buyingProcess: [
            {
                stage: '1. Nhận thức vấn đề',
                description: 'Khách hàng nhận ra cần giải pháp mới',
                duration: '2-4 tuần',
                activities: ['Đọc báo cáo ngành', 'Thảo luận nội bộ'],
                contentNeeded: ['Blog posts', 'Industry reports'],
                objections: ['Chưa phải ưu tiên'],
                successCriteria: 'Đồng ý đây là vấn đề cần giải quyết'
            },
            {
                stage: '2. Tìm kiếm giải pháp',
                description: 'So sánh các lựa chọn có sẵn',
                duration: '2-6 tuần',
                activities: ['Google search', 'Demo request', 'Hỏi peer'],
                contentNeeded: ['So sánh sản phẩm', 'Demo', 'Free trial'],
                objections: ['Quá nhiều lựa chọn'],
                successCriteria: 'Shortlist 2-3 vendors'
            },
            {
                stage: '3. Đánh giá chi tiết',
                description: 'POC và đánh giá kỹ thuật',
                duration: '2-4 tuần',
                activities: ['POC', 'Reference calls', 'Negotiation'],
                contentNeeded: ['Technical docs', 'Customer references'],
                objections: ['Tính năng thiếu', 'Giá cao'],
                successCriteria: 'Chọn preferred vendor'
            },
            {
                stage: '4. Quyết định mua',
                description: 'Phê duyệt và ký hợp đồng',
                duration: '1-4 tuần',
                activities: ['Final negotiation', 'Legal review', 'Budget approval'],
                contentNeeded: ['Proposal', 'Contract', 'SLA'],
                objections: ['Budget freeze', 'Cần thêm approval'],
                successCriteria: 'Ký hợp đồng'
            },
            {
                stage: '5. Triển khai & Adoption',
                description: 'Onboarding và bắt đầu sử dụng',
                duration: '4-12 tuần',
                activities: ['Implementation', 'Training', 'Go-live'],
                contentNeeded: ['Onboarding guide', 'Training videos'],
                objections: ['Phức tạp', 'Nhân viên không muốn đổi'],
                successCriteria: 'Active usage'
            }
        ],
        purchaseBarriers: [
            { barrier: 'Ngân sách hạn chế', category: 'Price', severity: 'High', overcomingStrategy: 'Flexible payment, ROI calculator, pilot program', proofPoints: ['ROI case study', 'Payment plan options'] },
            { barrier: 'Sợ triển khai phức tạp', category: 'Complexity', severity: 'High', overcomingStrategy: 'Pre-built templates, dedicated CSM', proofPoints: ['2-week implementation avg', 'Customer success stories'] },
            { barrier: 'Đang dùng giải pháp khác', category: 'Competition', severity: 'Medium', overcomingStrategy: 'Free migration, parallel running', proofPoints: ['Migration guide', 'Zero-downtime guarantee'] },
            { barrier: 'Chính trị nội bộ', category: 'Politics', severity: 'Medium', overcomingStrategy: 'Stakeholder-specific materials', proofPoints: ['Role-based value props', 'Champion toolkit'] },
        ],
        buyingCommittee: {
            avgSize: 4,
            typicalCycle: '60 ngày',
            budgetHolder: 'CEO / CFO'
        },

        commonObjections: [
            { objection: 'Giá bên em đắt hơn bên kia', frequency: 80, category: 'Price', response: 'Total Cost of Ownership thấp hơn khi tính đầy đủ', proofPoints: ['TCO comparison', 'ROI calculator'] },
            { objection: 'Chúng tôi đang dùng giải pháp khác', frequency: 65, category: 'Competition', response: 'Hỗ trợ migration miễn phí, không downtime', proofPoints: ['Migration guide', 'Switch case studies'] },
            { objection: 'Cần hỏi ý kiến thêm người khác', frequency: 60, category: 'Decision Process', response: 'Chuẩn bị tài liệu cho từng stakeholder', proofPoints: ['Stakeholder decks', 'Executive summary'] },
            { objection: 'Bây giờ chưa phải thời điểm', frequency: 55, category: 'Timing', response: 'Flexible payment, cost of delay analysis', proofPoints: ['Cost of delay calculator', 'Quick start program'] },
        ],
        sentimentAnalysis: {
            overall: 0,
            positive: 0,
            neutral: 0,
            negative: 0,
            trend: 'Stable',
            topPositiveThemes: ['Chưa có dữ liệu sentiment thực tế'],
            topNegativeThemes: ['Chưa có dữ liệu sentiment thực tế']
        },
        featureRequests: [],
        npsScore: 0,

        executiveSummary: {
            overview: `Phân tích customer insights cho ${companyName} trong ngành ${industry} tại ${targetMarket}. ` +
                (ctx.totalCompanies > 0
                    ? `Database VICO có ${ctx.totalCompanies} công ty ${industry}. `
                    : '') +
                `Lưu ý: AI không khả dụng nên dữ liệu dựa trên industry benchmarks, không phải phân tích cụ thể.`,
            keyInsights: [
                `ICP: ${icp.firmographics.industries.slice(0, 3).join(', ')}`,
                `Pain point chính: ${painPoints[0]?.pain || 'Hiệu suất vận hành'}`,
                `Decision maker: ${icp.decisionMakers[0]?.title || 'CEO'}`,
                `Dữ liệu sentiment/NPS: chưa có — cần khảo sát thực tế`,
            ],
            recommendations: [
                `Tập trung vào trigger event "Tăng trưởng nhanh" để tiếp cận khách hàng`,
                `Xây dựng content giải quyết pain point "${painPoints[0]?.pain || 'hiệu suất'}"`,
                `Thu thập feedback thực tế để có NPS và sentiment chính xác`,
            ]
        }
    };
}

// ============================================================================
// MAIN EXPORT
// ============================================================================

export async function generateCustomerInsights(params: {
    companyName: string;
    industry?: string;
    products?: string;
    targetMarket?: string;
}): Promise<CustomerInsightsReport> {
    const { companyName, industry = 'Technology', products = '', targetMarket = 'Vietnam' } = params;

    console.log(`🎯 Customer Insights Request: ${companyName} (${industry})`);

    // 1. Find company in database
    let companyData: NormalizedCompany | null = null;
    try {
        const allCompanies = await loadAllCompanies();
        companyData = allCompanies.find(c =>
            c.name.toLowerCase().includes(companyName.toLowerCase()) ||
            companyName.toLowerCase().includes(c.name.toLowerCase())
        ) || null;
        if (companyData) {
            console.log(`   📊 Found company in database: ${companyData.name} (${companyData.industry})`);
        }
    } catch (err) {
        console.warn('   ⚠️ Could not load company database');
    }

    const detectedIndustry = companyData?.industry || industry;

    // 2. Build industry context from real database
    const industryCtx = await buildIndustryContext(detectedIndustry, companyName);
    console.log(`   📈 Industry context: ${industryCtx.totalCompanies} companies in ${detectedIndustry}`);

    // 3. Try AI analysis
    const aiInsights = await analyzeWithGemini(
        companyName, detectedIndustry, products, targetMarket, companyData, industryCtx
    );

    if (aiInsights) {
        // Successfully generated AI insights — map to typed report
        const report: CustomerInsightsReport = {
            generatedAt: new Date().toISOString(),
            companyName,
            industry: detectedIndustry,
            dataSource: 'ai_analysis',
            dataSources: [
                companyData ? 'VICO Company Database' : 'User input',
                'Gemini 2.0 Flash AI Analysis',
                industryCtx.totalCompanies > 0 ? `Industry data (${industryCtx.totalCompanies} companies)` : ''
            ].filter(Boolean),

            idealCustomerProfile: {
                firmographics: {
                    ...aiInsights.idealCustomerProfile.firmographics,
                    techMaturity: (aiInsights.idealCustomerProfile.firmographics.techMaturity as any) || 'Mainstream'
                },
                decisionMakers: (aiInsights.idealCustomerProfile.decisionMakers || []).map((dm: any) => ({
                    ...dm,
                    role: dm.role as any || 'Champion'
                })),
                keyInfluencers: (aiInsights.idealCustomerProfile.keyInfluencers || []).map((ki: any) => ({
                    ...ki,
                    influence: ki.influence as any || 'Medium'
                }))
            },
            userPersonas: aiInsights.userPersonas || [],

            painPoints: (aiInsights.painPoints || []).map((pp: any) => ({
                ...pp,
                severity: pp.severity as any || 'Medium'
            })),
            desiredOutcomes: aiInsights.desiredOutcomes || [],
            triggerEvents: (aiInsights.triggerEvents || []).map((te: any) => ({
                ...te,
                urgency: te.urgency as any || 'Short-term'
            })),

            buyingProcess: aiInsights.buyingProcess || [],
            purchaseBarriers: (aiInsights.purchaseBarriers || []).map((pb: any) => ({
                ...pb,
                category: pb.category as any || 'Complexity',
                severity: pb.severity as any || 'Medium'
            })),
            buyingCommittee: aiInsights.buyingCommittee || { avgSize: 4, typicalCycle: '60 ngày', budgetHolder: 'CEO' },

            commonObjections: aiInsights.commonObjections || [],
            sentimentAnalysis: {
                overall: aiInsights.sentimentAnalysis?.overall || 0,
                positive: aiInsights.sentimentAnalysis?.positive || 0,
                neutral: aiInsights.sentimentAnalysis?.neutral || 0,
                negative: aiInsights.sentimentAnalysis?.negative || 0,
                trend: (aiInsights.sentimentAnalysis?.trend as any) || 'Stable',
                topPositiveThemes: aiInsights.sentimentAnalysis?.topPositiveThemes || [],
                topNegativeThemes: aiInsights.sentimentAnalysis?.topNegativeThemes || []
            },
            featureRequests: (aiInsights.featureRequests || []).map((fr: any) => ({
                ...fr,
                priority: fr.priority as any || 'Medium',
                status: fr.status as any || 'Considering'
            })),
            npsScore: aiInsights.npsScore || 0,

            executiveSummary: aiInsights.executiveSummary || {
                overview: `Phân tích AI cho ${companyName}`,
                keyInsights: [],
                recommendations: []
            }
        };

        console.log(`✅ Customer Insights generated via AI for ${companyName}`);
        return report;
    }

    // 4. Fallback when AI unavailable
    console.log(`   ⚠️ Using fallback insights for ${companyName} (AI unavailable)`);
    return buildFallbackReport(companyName, detectedIndustry, products, targetMarket, industryCtx);
}

export default generateCustomerInsights;
